---
- name: Install Java (required for Jenkins)
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes

- name: Add Jenkins repo and key
  shell: |
    curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee \
      /usr/share/keyrings/jenkins-keyring.asc > /dev/null
    echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
      https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
      /etc/apt/sources.list.d/jenkins.list > /dev/null

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Ensure Jenkins service is running
  service:
    name: jenkins
    state: started
    enabled: yes

