---
- name: Configure Nginx Web Server
  hosts: webservers
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Customize the index page
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head>
            <title>Welcome to Yasmin's Web Server</title>
          </head>
          <body style="background-color:black; color:white; text-align:center; font-family:Arial;">
            <h1>Hello from Ansible!</h1>
            <h2>Automated by Yasmin Atef 💻</h2>
          </body>
          </html>

    - name: Ensure Nginx is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes

